const scrollContainer = document.getElementById("scroll-container");
const navButtons = Array.from(document.querySelectorAll("[data-page]"));

const STORAGE_KEY = "rag-ai-scroll-state";

const pageData = {
  home: {
    steps: [
      { key: "hero", eyebrow: "Scroll engine", title: "One active step at a time", copy: "This page proves the refinement spec: a fixed header, a sticky stage, and a step state machine that responds to both scroll and buttons.", detail: "The visible surface stays locked to a single slide while the scroll track advances the narrative underneath it.", stickyTitle: "Fixed header, isolated stage", stickyCopy: "Only one slide is active. The previous and next steps stay out of view until the state changes.", tags: ["Fixed header", "One state", "No overlap"] },
      { key: "problem", eyebrow: "Why it matters", title: "Continuous pages are hard to scan", copy: "Long unbroken pages make it easy to lose the thread. A slide model keeps the next action obvious and reduces visual noise.", detail: "The scroll track still exists, but it advances discrete slides instead of exposing partial neighboring content.", stickyTitle: "Better legibility", stickyCopy: "Each step gets its own viewport-sized canvas, so the message lands before the next change.", tags: ["Readable", "Predictable", "Focused"] },
      { key: "solution", eyebrow: "Design choice", title: "Hybrid scroll and buttons", copy: "The active slide can move with scrolling or with explicit controls. Both routes use the same state source, so the UI never drifts.", detail: "That keeps the interaction simple: scroll for discovery, buttons for precision.", stickyTitle: "Single source of truth", stickyCopy: "The buttons and the observer both point at the same active step value.", tags: ["Sync", "Buttons", "Scroll"] },
      { key: "pipeline", eyebrow: "Pipeline", title: "The narrative steps map to the RAG flow", copy: "Ingest, chunk, embed, retrieve, and answer remain the conceptual backbone. Each stage gets its own slide state.", detail: "The right panel highlights the current state and exposes quick navigation to every other step.", stickyTitle: "RAG flow rail", stickyCopy: "The current step is highlighted while the other steps stay available as jumps.", tags: ["Ingest", "Chunk", "Embed", "Retrieve", "Answer"] },
      { key: "answer", eyebrow: "Outcome", title: "The assistant answers from grounded evidence", copy: "The final slide closes the loop: retrieved evidence feeds the answer, and the UI makes that progression easy to follow.", detail: "This keeps the presentation focused on the architecture instead of on decorative motion.", stickyTitle: "Grounded answers", stickyCopy: "The final step emphasizes evidence-first response generation.", tags: ["Grounded", "Evidence-first", "Final state"] }
    ]
  },
  technical: {
    steps: [
      { key: "overview", eyebrow: "Architecture", title: "Native DOM frontend, same-origin backend", copy: "The app renders directly in the browser with FastAPI serving the HTML, CSS, and JavaScript from the same origin as the API.", detail: "That removes the old embedding layer and keeps the frontend contract simple.", stickyTitle: "One origin", stickyCopy: "The UI and the API live together, so navigation and data flow stay straightforward.", tags: ["FastAPI", "Native DOM", "Same origin"] },
      { key: "ingestion", eyebrow: "Ingestion", title: "Uploads go straight to the existing API", copy: "The workspace panel still uploads files to the established ingestion route. The cleanup pass only changed the presentation layer.", detail: "Backend behavior stays untouched; the client just speaks to the same route in a cleaner shell.", stickyTitle: "Upload pipeline", stickyCopy: "Files are posted directly to the current ingestion endpoint.", tags: ["POST /upload", "Existing route", "No backend rewrite"] },
      { key: "chunking", eyebrow: "Processing", title: "Chunks are created before retrieval", copy: "Document processing still runs through chunking and embedding before the retrieval layer sees the result.", detail: "That preserves the original RAG workflow while the UI narrates it more cleanly.", stickyTitle: "Chunk first", stickyCopy: "The process stays evidence-driven before any generated answer appears.", tags: ["Chunking", "Embeddings", "Grounding"] },
      { key: "embeddings", eyebrow: "Representation", title: "Embeddings power semantic retrieval", copy: "The narrative explains how meaning, not just keyword overlap, drives the relevant passage selection.", detail: "That makes the interface a better teaching tool for the retrieval layer.", stickyTitle: "Semantic layer", stickyCopy: "The right answer comes from meaningful similarity, not simple string matching.", tags: ["Vectors", "Similarity", "Semantics"] },
      { key: "retrieval", eyebrow: "Retrieval", title: "The retriever surfaces the best passages", copy: "The model is only asked to answer after the most relevant passages are found. The active slide reinforces that order.", detail: "Each navigation change updates the highlighted step and the explanatory panel together.", stickyTitle: "Evidence selection", stickyCopy: "The retriever chooses context before generation begins.", tags: ["Top-k", "Sources", "Context"] },
      { key: "response", eyebrow: "Response", title: "Generation stays grounded in source context", copy: "The final stage returns the answer and the supporting passages, which the workspace panel can display after a query.", detail: "The cleanup pass keeps the read path and the workspace interactions aligned with the old backend contract.", stickyTitle: "Answer + sources", stickyCopy: "The response explains itself through the retrieved passages.", tags: ["Answer", "Sources", "Traceable"] }
    ]
  },
  workspace: {
    introTitle: "Upload documents and ask grounded questions",
    introCopy: "The backend remains unchanged. This panel only talks to the existing ingestion, query, and reset routes.",
    steps: []
  }
};

const state = {
  page: resolvePageFromLocation(),
  activeStep: 0,
  renderToken: 0,
  scrollMemory: loadScrollMemory(),
  observer: null,
  scrollListenerAttached: false,
  controlsBound: false
};

function escapeHtml(value) {
  return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
}
function clamp(value, min, max) { return Math.min(Math.max(value, min), max); }
function loadScrollMemory() { try { const raw = window.localStorage.getItem(STORAGE_KEY); return raw ? JSON.parse(raw) : {}; } catch { return {}; } }
function saveScrollMemory() { try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state.scrollMemory)); } catch {} }
function resolvePageFromLocation() { const path = window.location.pathname.replace(/\/+$/, "") || "/"; if (path === "/technical") return "technical"; if (path === "/workspace") return "workspace"; return "home"; }
function pagePath(pageName) { if (pageName === "technical") return "/technical"; if (pageName === "workspace") return "/workspace"; return "/"; }
function syncNavState(pageName) { navButtons.forEach((button) => button.classList.toggle("is-active", button.dataset.page === pageName)); }
function getSteps(pageName) { return pageData[pageName]?.steps || []; }
function getStep(pageName, index) { return getSteps(pageName)[index] || null; }
function renderTagList(tags = []) { return tags.map((tag) => `<span class="tag-chip">${escapeHtml(tag)}</span>`).join(""); }
function buildStepTriggers(pageName) { return getSteps(pageName).map((step, index) => `<section class="step-trigger" data-step="${index}" aria-hidden="true"><span class="visually-hidden">${escapeHtml(step.eyebrow)} ${escapeHtml(step.title)}</span></section>`).join(""); }
function buildFlowPanel(pageName, step, activeIndex) { const steps = getSteps(pageName); return `<section class="flow-panel"><p class="flow-panel__eyebrow">${pageName === "home" ? "Story rail" : "Engineering rail"}</p><div class="flow-panel__frame"><p class="flow-panel__label">Current step</p><h4>${escapeHtml(step.stickyTitle)}</h4><p>${escapeHtml(step.stickyCopy)}</p></div><div class="flow-panel__dots" aria-label="Step rail">${steps.map((item, index) => `<button class="flow-chip ${index === activeIndex ? "is-active" : ""}" type="button" data-step-nav="${index}" aria-label="Jump to ${escapeHtml(item.title)}">${String(index + 1).padStart(2, "0")}</button>`).join("")}</div><div class="step-actions"><button class="step-action" type="button" data-step-nav="${Math.max(activeIndex - 1, 0)}" ${activeIndex === 0 ? "disabled" : ""}>Previous Step</button><button class="step-action step-action--primary" type="button" data-step-nav="${Math.min(activeIndex + 1, steps.length - 1)}" ${activeIndex === steps.length - 1 ? "disabled" : ""}>Next Step</button></div></section>`; }
function buildSlideMarkup(pageName, step, activeIndex) { const indexLabel = String(activeIndex + 1).padStart(2, "0"); return `<div class="slide-shell"><section class="slide-copy"><p class="slide-kicker">${escapeHtml(step.eyebrow)}</p><h2>${escapeHtml(step.title)}</h2><p class="slide-lead">${escapeHtml(step.copy)}</p><p class="slide-detail">${escapeHtml(step.detail)}</p><div class="tag-row">${renderTagList(step.tags || [])}</div><div class="slide-meta"><span>Step ${indexLabel}</span><span>${pageName === "home" ? "Home narrative" : "Technical narrative"}</span></div></section><aside class="slide-visual">${buildFlowPanel(pageName, step, activeIndex)}</aside></div>`; }
function buildWorkspaceShell() { const page = pageData.workspace; return `<section class="page workspace-page" data-page="workspace"><div class="workspace-shell"><section class="workspace-panel workspace-upload"><p class="page-kicker">Workspace</p><h2>${escapeHtml(page.introTitle)}</h2><p>${escapeHtml(page.introCopy)}</p><form class="workspace-form" id="workspace-upload-form"><input class="workspace-file" type="file" id="workspace-files" multiple accept=".pdf,.txt" /><div class="workspace-actions"><button class="primary-button" type="submit">Upload</button><button class="secondary-button" type="button" id="workspace-reset">Reset index</button></div></form></section><section class="workspace-panel workspace-chat"><h4>Ask a question</h4><form class="workspace-form" id="workspace-query-form"><textarea class="workspace-input" id="workspace-question" placeholder="Ask about your documents..."></textarea><div class="workspace-actions"><button class="primary-button" type="submit">Ask</button></div></form><div class="workspace-feed" id="workspace-feed" aria-live="polite"></div></section><aside class="workspace-panel workspace-sources"><h4>Sources</h4><p>Retrieved passages appear here after a question is answered.</p><div class="workspace-tag-row"><span class="workspace-tag">UI only</span><span class="workspace-tag">Backend untouched</span><span class="workspace-tag">Same origin</span></div></aside></div></section>`; }
function buildPageShell(pageName) { if (pageName === "workspace") return buildWorkspaceShell(); const steps = getSteps(pageName); return `<section class="page page--${pageName}" data-page="${pageName}" style="--step-count:${steps.length};"><div class="scrolly-shell"><aside class="sticky-stage" id="sticky-stage" aria-live="polite"><div class="sticky-stage__inner" id="sticky-stage-inner"></div></aside><div class="step-track" aria-hidden="true">${buildStepTriggers(pageName)}</div></div></section>`; }
function renderSticky(step, pageName, instant = false) { const sticky = document.getElementById("sticky-stage-inner"); if (!sticky) return; const markup = buildSlideMarkup(pageName, step, state.activeStep); const token = ++state.renderToken; if (instant) { sticky.innerHTML = markup; return; } sticky.classList.add("is-transitioning"); window.setTimeout(() => { if (token !== state.renderToken) return; sticky.innerHTML = markup; window.requestAnimationFrame(() => sticky.classList.remove("is-transitioning")); }, 110); }
function clearObserver() { if (!state.observer) return; state.observer.disconnect(); state.observer = null; }
function setActiveSections(index) { Array.from(scrollContainer.querySelectorAll("[data-step]")).forEach((section) => section.classList.toggle("is-active", Number(section.dataset.step) === index)); }
function scrollToStep(index) { const target = scrollContainer.querySelector(`[data-step="${index}"]`); if (target) target.scrollIntoView({ behavior: "smooth", block: "start" }); }
function applyStep(index, { pageName = state.page, source = "scroll", syncScroll = false } = {}) { const step = getStep(pageName, index); if (!step) return; const changed = pageName !== state.page || index !== state.activeStep; state.page = pageName; state.activeStep = index; document.documentElement.dataset.currentStep = String(index); setActiveSections(index); if (changed) renderSticky(step, pageName, source === "init"); if (syncScroll) scrollToStep(index); }
function getStepIndexFromScroll(pageName) { const steps = getSteps(pageName); if (!steps.length) return 0; const height = Math.max(scrollContainer.clientHeight, 1); return clamp(Math.round(scrollContainer.scrollTop / height), 0, steps.length - 1); }
function setupScrollEngine() { clearObserver(); const sections = Array.from(scrollContainer.querySelectorAll("[data-step]")); if (!sections.length) return; state.observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((left, right) => right.intersectionRatio - left.intersectionRatio)[0]; if (!visible) return; const nextIndex = Number(visible.target.dataset.step); if (Number.isNaN(nextIndex)) return; applyStep(nextIndex, { pageName: state.page, source: "scroll" }); }, { root: scrollContainer, threshold: [0.35, 0.55, 0.75] }); sections.forEach((section) => state.observer.observe(section)); }
function persistScroll() { state.scrollMemory[state.page] = scrollContainer.scrollTop; saveScrollMemory(); }
function restoreScroll(pageName) { scrollContainer.scrollTop = Number(state.scrollMemory[pageName] || 0); }
function bindScrollTracking() { if (state.scrollListenerAttached) return; scrollContainer.addEventListener("scroll", persistScroll, { passive: true }); scrollContainer.addEventListener("scroll", () => { if (state.page === "workspace") return; window.requestAnimationFrame(() => applyStep(getStepIndexFromScroll(state.page), { pageName: state.page, source: "scroll" })); }, { passive: true }); state.scrollListenerAttached = true; }
function bindStepControls() { if (state.controlsBound) return; scrollContainer.addEventListener("click", (event) => { const button = event.target.closest("[data-step-nav]"); if (!button || button.disabled) return; const nextIndex = Number(button.dataset.stepNav); if (Number.isNaN(nextIndex)) return; applyStep(nextIndex, { pageName: state.page, source: "button", syncScroll: true }); }); state.controlsBound = true; }
function renderWorkspaceFeed(message, role = "assistant") { const feed = document.getElementById("workspace-feed"); if (!feed) return; const node = document.createElement("article"); node.className = "feed-message"; node.dataset.role = role; node.innerHTML = `<strong>${role === "user" ? "You" : "Assistant"}</strong><p>${escapeHtml(message)}</p>`; feed.appendChild(node); feed.scrollTop = feed.scrollHeight; }
function renderSources(sources = []) { const sourcePanel = document.querySelector(".workspace-sources"); if (!sourcePanel) return; const existing = sourcePanel.querySelector(".source-list"); if (existing) existing.remove(); const list = document.createElement("ol"); list.className = "source-list"; list.innerHTML = sources.map((item) => `<li>${escapeHtml(item.text || "")}</li>`).join(""); sourcePanel.appendChild(list); }
async function uploadDocuments(files) { const results = []; for (const file of files) { const formData = new FormData(); formData.append("file", file); const response = await fetch("/upload", { method: "POST", body: formData }); if (!response.ok) { const text = await response.text(); throw new Error(text || `Upload failed for ${file.name}`); } results.push(await response.json()); } return results; }
async function resetIndex() { const response = await fetch("/reset", { method: "POST" }); if (!response.ok) throw new Error("Reset failed"); }
async function askQuestion(question) { const response = await fetch("/query", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question, top_k: 4 }) }); if (!response.ok) throw new Error("Query failed"); return response.json(); }
function bindWorkspace() { const uploadForm = document.getElementById("workspace-upload-form"); const queryForm = document.getElementById("workspace-query-form"); const resetButton = document.getElementById("workspace-reset"); const questionInput = document.getElementById("workspace-question"); const fileInput = document.getElementById("workspace-files"); if (uploadForm) uploadForm.addEventListener("submit", async (event) => { event.preventDefault(); const files = Array.from(fileInput.files || []); if (!files.length) { renderWorkspaceFeed("Choose one or more files before uploading.", "assistant"); return; } renderWorkspaceFeed(`Uploading ${files.length} file(s)...`, "assistant"); try { const responses = await uploadDocuments(files); const chunkCount = responses.reduce((total, item) => total + Number(item.chunks_added || 0), 0); renderWorkspaceFeed(`Indexed ${chunkCount} chunks.`, "assistant"); } catch (error) { renderWorkspaceFeed(error.message, "assistant"); } }); if (queryForm) queryForm.addEventListener("submit", async (event) => { event.preventDefault(); const question = questionInput.value.trim(); if (!question) return; renderWorkspaceFeed(question, "user"); questionInput.value = ""; try { const data = await askQuestion(question); renderWorkspaceFeed(data.answer || "No answer returned.", "assistant"); renderSources(data.sources || []); } catch (error) { renderWorkspaceFeed(error.message, "assistant"); } }); if (resetButton) resetButton.addEventListener("click", async () => { try { await resetIndex(); const feed = document.getElementById("workspace-feed"); if (feed) feed.innerHTML = ""; renderWorkspaceFeed("Index cleared.", "assistant"); renderSources([]); } catch (error) { renderWorkspaceFeed(error.message, "assistant"); } }); }
function showPage(pageName, pushState) { const nextPage = pageData[pageName] ? pageName : "home"; state.page = nextPage; syncNavState(nextPage); if (pushState) history.pushState({ page: nextPage }, "", pagePath(nextPage)); scrollContainer.innerHTML = buildPageShell(nextPage); bindScrollTracking(); bindStepControls(); clearObserver(); if (nextPage === "workspace") { bindWorkspace(); restoreScroll(nextPage); return; } state.activeStep = 0; document.documentElement.dataset.currentStep = "0"; setupScrollEngine(); renderSticky(getStep(nextPage, 0), nextPage, true); restoreScroll(nextPage); window.requestAnimationFrame(() => applyStep(getStepIndexFromScroll(nextPage), { pageName: nextPage, source: "scroll" })); }
function bindNavigation() { navButtons.forEach((button) => button.addEventListener("click", () => showPage(button.dataset.page, true))); window.addEventListener("popstate", () => showPage(resolvePageFromLocation(), false)); }
function init() { syncNavState(state.page); bindNavigation(); showPage(state.page, false); }
init();
